name: Go Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
