name: Release Go Binaries

on: 
  release:
    types: [created]
  workflow_dispatch:

env:
  CMD_PATH: ./cmd/deployer


jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:  
          # darwin/386, windows arm64 and linux/arm64 seems useless 
          - goarch: arm64
            goos: windows 
          - goarch: arm64
            goos: linux
          - goarch: "386"
            goos: darwin 

    steps:
    - uses: actions/checkout@v2

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Set BUILD_TIME env
      run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "${{ env.CMD_PATH }}"
        build_flags: -v
        ldflags: -X "main.version=${{ env.APP_VERSION }}{{ env.BUILD_TIME }}"
